### ISSUE TITLE
Possible missing inverse in LID computation

### ISSUE THREAD

**Issue by averyma** [xingjunm/lid_adversarial_subspace_detection#3]
While computing LID in `mle_single` and `mle_batch`, it seems that there is no inverse operation: `f = lambda v: - k / np.sum(np.log(v/v[-1]))`. However, it was stated in the paper that the LID is computed using the inverse of the summation term (Equation 4).

**Comment by xingjunm** [comment]
Hi Avery,
Note the inverse is already considered by -k/sum.

Best regards,
Daniel

**Comment by averyma** [comment]
> Hi Avery, Note the inverse is already considered by -k/sum. Best regards, Daniel

You are absolutely correct! I missed that :D
